#!/bin/zsh

# Various aliases
alias free="free -m"
alias grep="grep --color -i"
alias ls="ls --color=auto -CFh"
alias sl="ls --color=auto -CFh"
alias ll="ls -l"
alias vi=vim
alias viol='vim -c "source ~/.vim/outline.vimrc" $*'
alias vila="vim ~/.zsh/localalias; sz"
alias viga="vim ~/.zsh/globalalias; sz"
alias sz="source ~/.zshrc"

# load rarely used zsh functions
alias loadzftp="autoload -U zfinit && zfinit"
alias loadtcpopen="autoload -U tcp_open && tcp_open"

# global aliases
alias -g ...="../.."
alias -g ....="../../.."
alias -g .....="../../../.."

# git aliases
alias gitp="git push -u origin master"
alias gita="git add"
alias gitc="git commit"
alias gitac="git commit -a"
alias gitr="git rm"
alias gitmv="git mv"
alias gitb="git branch"
alias gitm="git merge"

# Find shortcuts
function findi() {
		find . -iname "*${1}*"
	}

# Reverse Engineering Shortcuts

alias gdb="gdb -q"
